def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
    
num1=int(input("Enter first Number:"))
num2=int(input("Enter second Number:"))
print("Thanks for giving two numbers And i initiated The arthamatic operator.")

print("Addition :", add(num1,num2))
print("Substraction :",sub(num1,num2))
print("Multiplication :",mul(num1,num2))
print("Division :",div(num1,num2))