marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A  AND He Was An BRILIANT STUDENT!")
elif marks >= 75:
    print("Grade B AND He Was An TOPPER STUDENT!")
elif marks >= 60:
    print("Grade C AND He Was An AVERAGE STUDENT!")
elif marks >= 35:
    print("Grade D AND He Was An MEDIUM STUDENT!")
else:
    print("Fail AND He Was An IMPROVES IN STUDIES FOR THIS STUDENT!")
