#write a program to input eight numbers from the user and display all the unique numbers ?

s=set()

n=int(input("enter your 1 st number"))
s.add(int(n))

n=int(input("enter your 2 nd number"))
s.add(int(n))

n=int(input("enter your 3 rd number"))
s.add(int(n))

n=int(input("enter your 4 th number"))
s.add(int(n))

n=int(input("enter your 5 th number"))
s.add(int(n))

n=int(input("enter your 6 th number"))
s.add(int(n))

n=int(input("enter your 7 th number"))
s.add(int(n))



n=int(input("enter your 8 th number"))
s.add(int(n))

print(s)